### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by dezoonvandesi** [GoumJer/domoticz_energy_prices#1]
I'm getting this error when I run ./update_domoticz_costs.sh. I use the idx of the custom sensor I use to show my kWh info from my P1 meter.

`./update_domoticz_costs.sh: regel 114: printf: .079231: ongeldig getal
{
	"status" : "ERR"
}
cut: ongeldige veldwaarde 'Energie'
Typ 'cut --help' voor meer informatie.
(standard_in) 2: syntax error
(standard_in) 2: syntax error
{
	"status" : "ERR"
}`

Any thoughts?

**Comment by GoumJer** [comment]
My first guess something goes wrong on collection the current value of the cost counter.

Can you please run the script in debug mode and post the results?

`./update_domoticz_costs.sh Y`

Jeroen

**Comment by dezoonvandesi** [comment]
Here you go:

`-----
myHourStart: 2023-01-15 16:00
myTSStart: zo 15 jan 2023 16:00:00
HourEnd: 2023-01-15 17:00
myDate: ./20230115
myHour: 16
-----
HourStart: 2023-01-15 16:00
HourEnd: 2023-01-15 17:00
-----
myStartValue: 5737
MyEndValue: 6408
MyReturnStart:
MyReturnEnd:
-----
myUsageWH: 671
UsageKWH: .6710
-----
Price: 0.288631
UsageKWH: .6710
Costs: .193671
myDayCost: null
./update_domoticz_costs.sh: regel 114: printf: .193671: ongeldig getal
myNewCosts: 0,00
{
	"status" : "ERR"
}
cut: ongeldige veldwaarde 'Energie'
Typ 'cut --help' voor meer informatie.
(standard_in) 2: syntax error
-----
Price:
UsageKWH: .6710
Costs:
myDayCost: null
(standard_in) 2: syntax error
myNewCosts: 0,00
{
	"status" : "ERR"
}`

**Comment by GoumJer** [comment]
Looks like the script is failing on retreiving the last value of the cost_counter (which is null).

Can you execute the following url in a browser, modifying the domoticz.url and YourIDX to your situation? Use the indexnumber of the cost sensor

`http://domoticz.url:8080/json.htm?type=command&param=udevice&idx=YourIDX&nvalue=0&svalue=0`

Then try the update_domoticz_costs script again.

Besides this issue, I found 1 myself, cost calculation is not working on rollover to the next day :-(. Working on that issue

**Comment by dezoonvandesi** [comment]
Still the same error

`myHourStart: 2023-01-16 10:00
myTSStart: ma 16 jan 2023 10:00:00
HourEnd: 2023-01-16 11:00
myDate: ./20230116
myHour: 10
-----
HourStart: 2023-01-16 10:00
HourEnd: 2023-01-16 11:00
-----
myStartValue: 1928
MyEndValue: 2881
MyReturnStart:
MyReturnEnd:
-----
myUsageWH: 953
UsageKWH: .9530
-----
Price: 0.415802
UsageKWH: .9530
Costs: .396259
myDayCost: null
./update_domoticz_costs.sh: regel 114: printf: .396259: ongeldig getal
myNewCosts: 0,00
{
	"status" : "ERR"
}
cut: ongeldige veldwaarde 'Energie'
Typ 'cut --help' voor meer informatie.
(standard_in) 2: syntax error
-----
Price:
UsageKWH: .9530
Costs:
myDayCost: null
(standard_in) 2: syntax error
myNewCosts: 0,00
{
	"status" : "ERR"
}
`

**Comment by GoumJer** [comment]
It's clear that retreiving the daily costs until the last hour goes wrong...

Can you please try (replacing both variables with the correct value):

`curl -s "$myDomoticzURL/json.htm?type=graph&sensor=Percentage&idx=$myProviderCostsDayIDX&range=day"`

This should give a data entry for every 5 minutes from the last 24 hours.

If this gives result, try:

`curl -s "$myDomoticzURL/json.htm?type=graph&sensor=Percentage&idx=$myProviderCostsDayIDX&range=day"|jq -r '.result[-1]|.'`

**Comment by dezoonvandesi** [comment]
The first command gave results back, so here's the result form the second command:

`{
  "d": "2023-01-16 12:10",
  "v": "0.0"
}`

**Comment by GoumJer** [comment]
This is what I expect, so curious what is going wrong?

From your error:
```
myDayCost: null
./update_domoticz_costs.sh: regel 114: printf: .396259: ongeldig getal
myNewCosts: 0,00
```

Retreiving the costs until today is going wrong. Can you please test by setting the value to 1 and test? Just to see what happens?

`http://domoticz.url:8080/json.htm?type=command&param=udevice&idx=YourIDX&nvalue=0&svalue=1`

**Comment by dezoonvandesi** [comment]
Still the same error

**Comment by GoumJer** [comment]
Hmm, this is getting more strange...

But... on the Domoticz Forum I got hinted for a much better calculation of the prices. I'm currently trying to understand the script and modifying to work accoding my wishes. First testrun's are ok, wondering what it will do on dayly rollover at 00:00.

If this works, it will also solve the problem you're running into, because it is running inside Domoticz (dzvents script).

[Click here for the forum thread](https://www.domoticz.com/forum/viewtopic.php?t=39767)

**Comment by dezoonvandesi** [comment]
Sounds great!

**Comment by GoumJer** [comment]
New scripts uploaded for costcalculation via dzvents script. Closing this issue since it is no more relevant

**Comment by pergotje** [comment]
> cut: ongeldige veldwaarde 'Energie'
> Typ 'cut --help' voor meer informatie.
> (standard_in) 2: syntax error

This is because the provider name in enever.conf may not contain a space.
